import 'dart:convert';

import 'package:ai_orchestrator/app_factory/workshop/workshop_library_github_auth.dart';
import 'package:http/http.dart' as http;
import 'package:http/testing.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  group('WorkshopLibraryGitHubAuthClient', () {
    final fixedNow = DateTime.utc(2026, 9, 13, 20);

    test('requests device code with client id only and trusted GitHub URI', () async {
      final client = MockClient((request) async {
        expect(request.url.toString(), 'https://github.com/login/device/code');
        final fields = Uri.splitQueryString(request.body);
        expect(fields['client_id'], 'Iv1.client');
        expect(fields.containsKey('client_secret'), isFalse);
        return http.Response(
          jsonEncode(<String, Object?>{
            'device_code': 'device-code',
            'user_code': 'ABCD-EFGH',
            'verification_uri': 'https://github.com/login/device',
            'expires_in': 900,
            'interval': 5,
          }),
          200,
        );
      });
      final auth = WorkshopLibraryGitHubAuthClient(
        client: client,
        now: () => fixedNow,
      );

      final result = await auth.requestDeviceAuthorization(clientId: 'Iv1.client');
      expect(result.deviceCode, 'device-code');
      expect(result.userCode, 'ABCD-EFGH');
      expect(result.verificationUri.host, 'github.com');
      expect(result.interval, const Duration(seconds: 5));
      expect(result.expiresAt, fixedNow.add(const Duration(seconds: 900)));
    });

    test('maps pending and slow-down without exposing secrets', () async {
      var call = 0;
      final client = MockClient((request) async {
        final fields = Uri.splitQueryString(request.body);
        expect(fields.containsKey('client_secret'), isFalse);
        call += 1;
        return http.Response(
          jsonEncode(
            call == 1
                ? <String, Object?>{'error': 'authorization_pending'}
                : <String, Object?>{'error': 'slow_down', 'interval': 10},
          ),
          200,
        );
      });
      final auth = WorkshopLibraryGitHubAuthClient(client: client);

      final pending = await auth.pollDeviceAuthorization(
        clientId: 'client',
        deviceCode: 'device',
      );
      expect(pending.state, WorkshopGitHubDevicePollState.authorizationPending);
      expect(pending.credential, isNull);

      final slow = await auth.pollDeviceAuthorization(
        clientId: 'client',
        deviceCode: 'device',
      );
      expect(slow.state, WorkshopGitHubDevicePollState.slowDown);
      expect(slow.minimumInterval, const Duration(seconds: 10));
    });

    test('returns expiring GitHub user credential after authorization', () async {
      final client = MockClient((request) async {
        return http.Response(
          jsonEncode(<String, Object?>{
            'access_token': 'ghu_access_secret',
            'token_type': 'bearer',
            'expires_in': 28800,
            'refresh_token': 'ghr_refresh_secret',
            'refresh_token_expires_in': 15897600,
            'scope': '',
          }),
          200,
        );
      });
      final auth = WorkshopLibraryGitHubAuthClient(
        client: client,
        now: () => fixedNow,
      );
      final result = await auth.pollDeviceAuthorization(
        clientId: 'client',
        deviceCode: 'device',
      );

      expect(result.state, WorkshopGitHubDevicePollState.authorized);
      expect(result.credential?.accessToken, 'ghu_access_secret');
      expect(result.credential?.refreshToken, 'ghr_refresh_secret');
      expect(
        result.credential?.expiresAt,
        fixedNow.add(const Duration(seconds: 28800)),
      );
    });

    test('refresh generated by device flow also sends no client secret', () async {
      final client = MockClient((request) async {
        final fields = Uri.splitQueryString(request.body);
        expect(fields['client_id'], 'client');
        expect(fields['grant_type'], 'refresh_token');
        expect(fields['refresh_token'], 'ghr_old');
        expect(fields.containsKey('client_secret'), isFalse);
        return http.Response(
          jsonEncode(<String, Object?>{
            'access_token': 'ghu_new',
            'token_type': 'bearer',
            'expires_in': 28800,
            'refresh_token': 'ghr_new',
            'refresh_token_expires_in': 15897600,
          }),
          200,
        );
      });
      final auth = WorkshopLibraryGitHubAuthClient(client: client);
      final credential = await auth.refresh(
        clientId: 'client',
        refreshToken: 'ghr_old',
      );
      expect(credential.accessToken, 'ghu_new');
      expect(credential.refreshToken, 'ghr_new');
    });
  });

  group('WorkshopLibraryGitHubCredentialStore', () {
    test('persists token only through secret storage and exposes metadata snapshot', () async {
      final storage = _MemorySecretStorage();
      final store = WorkshopLibraryGitHubCredentialStore(storage: storage);
      final expiresAt = DateTime.now().toUtc().add(const Duration(hours: 1));
      final refreshExpiresAt =
          DateTime.now().toUtc().add(const Duration(days: 30));

      await store.save(
        WorkshopGitHubUserCredential(
          accessToken: 'ghu_private',
          refreshToken: 'ghr_private',
          expiresAt: expiresAt,
          refreshExpiresAt: refreshExpiresAt,
        ),
      );

      expect(storage.values.length, 1);
      final stored = storage.values.values.single;
      expect(stored, contains('ghu_private'));
      expect(stored, contains('ghr_private'));

      final snapshot = await store.snapshot();
      expect(snapshot.configured, isTrue);
      expect(snapshot.expiresAt, expiresAt);
      expect(snapshot.refreshExpiresAt, refreshExpiresAt);

      final loaded = await store.load();
      expect(loaded?.accessToken, 'ghu_private');
      expect(loaded?.refreshToken, 'ghr_private');

      await store.clear();
      expect(await store.load(), isNull);
    });

    test('corrupt secure-storage payload fails closed as not configured', () async {
      final storage = _MemorySecretStorage();
      final store = WorkshopLibraryGitHubCredentialStore(storage: storage);
      storage.values['ai_orchestrator.workshop.library.github.v1'] = '{bad';
      expect((await store.snapshot()).configured, isFalse);
      expect(await store.load(), isNull);
    });
  });
}

final class _MemorySecretStorage implements WorkshopLibrarySecretStorage {
  final Map<String, String> values = <String, String>{};

  @override
  Future<String?> read(String key) async => values[key];

  @override
  Future<void> write(String key, String value) async {
    values[key] = value;
  }

  @override
  Future<void> delete(String key) async {
    values.remove(key);
  }
}
