include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    prefer_const_constructors: info
    prefer_const_literals_to_create_immutables: info

linter:
  rules:
    - avoid_print
    - prefer_const_constructors
    - prefer_final_fields
    - use_super_parameters
    - always_use_package_imports
