import 'package:flutter/widgets.dart';

class AppLocalizations {
  AppLocalizations(this.locale);

  final Locale locale;

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static AppLocalizations of(BuildContext context) {
    final result = Localizations.of<AppLocalizations>(context, AppLocalizations);
    assert(result != null, 'AppLocalizations not found in context');
    return result!;
  }

  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'settings': 'Settings',
      'models': 'Models',
      'models_subtitle': 'Manage AI models',
      'personal_data_subtitle': 'Profile & preferences',
      'language_subtitle': 'App language',
      'ai_mode_subtitle': 'Runtime routing & fallback',
      'system_prompt_subtitle': 'Global AI behaviour',
      'settings_save_failed': 'Failed to save settings',
      'model_validated': 'Valid',
      'model_invalid': 'Invalid file',
      'import_url': 'Import URL',
      'import_local_model': 'Import GGUF',
      'imported_model': 'Imported',
      'local_model_path': 'Path',
      'model_missing_file': 'Missing file',
      'relink_model': 'Re-link',
      'refresh_models': 'Refresh models',
      'personal_data_optional': 'Personal Data (optional)',
      'name': 'Name',
      'date_of_birth': 'Date of birth',
      'profile_data_optional': 'Profile data (optional)',
      'language': 'Language',
      'system_default': 'System default',
      'english': 'English',
      'french': 'French',
      'italian': 'Italian',
      'spanish': 'Spanish',
      'german': 'German',
      'ai_mode': 'AI Mode',
      'fast': 'Fast',
      'balanced': 'Balanced',
      'deep_reasoning': 'Deep reasoning',
      'system_prompt': 'System Prompt',
      'define_global_ai_behavior': 'Define global AI behavior...',
      'reset_default': 'Reset default',
      'save': 'Save',
      'close': 'Close',
      'install': 'Install',
      'settings_saved': 'Settings saved',
      'import_model_from_url': 'Import model from URL',
      'model_url': 'Model URL',
      'display_name_optional': 'Display name (optional)',
      'cancel': 'Cancel',
      'import': 'Import',
      'url_required': 'URL is required',
      'valid_http_url': 'Enter a valid http/https URL',
      'ai_orchestrator': 'AI Orchestrator',
      'chat': 'Chat',
      'start_conversation': 'Start a conversation',
      'no_local_model': 'No local model',
      'message_hint': 'Message\u2026',
      'select_ai_provider': 'Select AI Provider',
      'starting_local_intelligence': 'Starting local intelligence\u2026',
      'continue': 'Continue',
      'get_started': 'Get started',
      'tell_us_about_you': 'Tell us about you',
      'personalize_experience': 'Personalise your AI Orchestrator experience.',
      'your_name': 'Your name',
      'name_required': 'Name is required',
      'dob_ddmmyyyy': 'Date of birth (DD/MM/YYYY)',
      'dob_required': 'Date of birth is required',
      'welcome_subtitle': 'Your minimal AI workspace.',
      'checking_updates': 'Checking for model updates\u2026',
      'choose_model': 'Choose your AI model',
      'download_offline_model': 'Download one model for fully offline AI processing.',
      'recommended_for_device': 'Recommended for this device:',
      'recommended': 'Recommended',
      'active': 'Active',
      'download': 'Download',
      'use_this_model': 'Use this model',
      're_download': 'Re-download',
      'update_available': 'Update available',
      'update': 'Update',
      'later': 'Later',
      'details': 'Details',
      'new_model_version_title': 'New model version available',
      'new_model_version_body': 'A newer version is available for:',
      'update_model_confirm': 'Do you want to update now?',
      'runtime_routing_description':
          'Local mode uses on-device models only. Cloud mode prefers the selected cloud provider. Hybrid mode uses local first, then cloud when needed.',
      'local_ai_mode': 'Local',
      'cloud_ai_mode': 'Cloud',
      'hybrid_ai_mode': 'Hybrid',
      'preferred_cloud_provider': 'Preferred cloud provider',
      'preferred_cloud_provider_subtitle':
          'Used whenever cloud routing is available.',
      'updates': 'Updates',
      'updates_subtitle': 'Self-update channels and checks',
      'local_runtime': 'Local runtime',
      'voice_engine': 'Voice engine',
      'mode': 'Mode',
      'tokens': 'Tokens',
      'time': 'Time',
      'runtime_ready': 'Ready',
      'runtime_idle': 'Runtime idle',
      'runtime_unverified': 'Runtime unverified',
      'runtime_loading': 'Loading',
      'runtime_tokenizing': 'Tokenizing',
      'runtime_generating': 'Generating',
      'runtime_streaming': 'Streaming',
      'runtime_completed': 'Completed',
      'runtime_timed_out': 'Timed out',
      'runtime_stalled': 'Runtime stalled',
      'runtime_error': 'Runtime error',
      'runtime_missing_library': 'Missing library',
      'runtime_model_missing': 'Model missing',
      'runtime_failed': 'Runtime failed',
      'runtime_checked_automatically':
          'Native llama.cpp runtime is checked automatically at startup.',
      'chat_surface_tagline': 'Local-first • minimal • focused',
      'send_message': 'Send message',
      'enter_message_to_send': 'Enter a message to send',
      'release_channel': 'Release channel',
      'preferred_release_channel': 'Preferred release channel',
      'check_updates_now': 'Check now',
      'force_update': 'Force update',
      'force_update_started': 'Force update started.',
      'force_update_failed': 'Force update could not start.',
      'latest_known': 'Latest known',
      'last_checked': 'Last checked',
      'already_up_to_date': 'Already up to date',
      'update_check_completed': 'Update check completed',
      'update_download_title': 'Update download',
      'update_idle': 'Updates not checked yet',
      'up_to_date': 'App is up to date',
      'new_version_available': 'New version available',
      'update_incompatible': 'Current app version is not compatible',
      'downloading_update': 'Downloading update…',
      'ready_to_install': 'Ready to install',
      'update_error': 'Update error',
      'current_version': 'Current version',
      'latest_version': 'Latest version',
      'dismiss': 'Dismiss',
      'apk_downloaded': 'APK downloaded. Continue from Settings > Updates.',
      'installer_opened': 'Installer opened. Confirm installation on Android.',
    },
    'fr': {
      'settings': 'Param\u00e8tres',
      'models': 'Mod\u00e8les',
      'models_subtitle': 'G\u00e9rer les mod\u00e8les IA',
      'personal_data_subtitle': 'Profil et pr\u00e9f\u00e9rences',
      'language_subtitle': 'Langue de l\'application',
      'ai_mode_subtitle': 'Routage runtime et secours',
      'system_prompt_subtitle': 'Comportement global de l\'IA',
      'settings_save_failed': '\u00c9chec de l\'enregistrement',
      'model_validated': 'Valide',
      'model_invalid': 'Fichier invalide',
      'import_url': 'Importer URL',
      'import_local_model': 'Importer GGUF',
      'imported_model': 'Importé',
      'local_model_path': 'Chemin',
      'model_missing_file': 'Fichier manquant',
      'relink_model': 'Relier',
      'refresh_models': 'Actualiser les mod\u00e8les',
      'personal_data_optional': 'Donn\u00e9es personnelles (optionnel)',
      'name': 'Nom',
      'date_of_birth': 'Date de naissance',
      'profile_data_optional': 'Donn\u00e9es de profil (optionnel)',
      'language': 'Langue',
      'system_default': 'Par d\u00e9faut du syst\u00e8me',
      'english': 'Anglais',
      'french': 'Fran\u00e7ais',
      'italian': 'Italien',
      'spanish': 'Espagnol',
      'german': 'Allemand',
      'ai_mode': 'Mode IA',
      'fast': 'Rapide',
      'balanced': '\u00c9quilibr\u00e9',
      'deep_reasoning': 'Raisonnement approfondi',
      'system_prompt': 'Prompt syst\u00e8me',
      'define_global_ai_behavior': 'D\u00e9finir le comportement global de l\'IA...',
      'reset_default': 'R\u00e9initialiser',
      'save': 'Enregistrer',
      'settings_saved': 'Param\u00e8tres enregistr\u00e9s',
      'import_model_from_url': 'Importer un mod\u00e8le depuis une URL',
      'model_url': 'URL du mod\u00e8le',
      'display_name_optional': 'Nom d\'affichage (optionnel)',
      'cancel': 'Annuler',
      'import': 'Importer',
      'url_required': 'L\'URL est requise',
      'valid_http_url': 'Entrez une URL http/https valide',
      'ai_orchestrator': 'AI Orchestrator',
      'chat': 'Chat',
      'start_conversation': 'D\u00e9marrer une conversation',
      'no_local_model': 'Aucun mod\u00e8le local',
      'message_hint': 'Message\u2026',
      'select_ai_provider': 'S\u00e9lectionner un fournisseur IA',
      'starting_local_intelligence': 'D\u00e9marrage de l\'intelligence locale\u2026',
      'continue': 'Continuer',
      'get_started': 'Commencer',
      'tell_us_about_you': 'Parlez-nous de vous',
      'personalize_experience': 'Personnalisez votre exp\u00e9rience AI Orchestrator.',
      'your_name': 'Votre nom',
      'name_required': 'Le nom est obligatoire',
      'dob_ddmmyyyy': 'Date de naissance (JJ/MM/AAAA)',
      'dob_required': 'La date de naissance est obligatoire',
      'welcome_subtitle': 'Votre espace IA minimal.',
      'checking_updates': 'V\u00e9rification des mises \u00e0 jour des mod\u00e8les\u2026',
      'choose_model': 'Choisissez votre mod\u00e8le IA',
      'download_offline_model': 'T\u00e9l\u00e9chargez un mod\u00e8le pour un traitement IA enti\u00e8rement hors ligne.',
      'recommended_for_device': 'Recommand\u00e9 pour cet appareil :',
      'recommended': 'Recommand\u00e9',
      'active': 'Actif',
      'download': 'T\u00e9l\u00e9charger',
      'use_this_model': 'Utiliser ce mod\u00e8le',
      're_download': 'Re-t\u00e9l\u00e9charger',
      'update': 'Mettre \u00e0 jour',
      'later': 'Plus tard',
      'details': 'D\u00e9tails',
      'new_model_version_title': 'Nouvelle version de mod\u00e8le disponible',
      'new_model_version_body': 'Une nouvelle version est disponible pour :',
      'update_model_confirm': 'Voulez-vous mettre \u00e0 jour maintenant ?',
      'runtime_routing_description':
          'Le mode local utilise uniquement les mod\u00e8les sur l\u2019appareil. Le mode cloud privil\u00e9gie le fournisseur cloud s\u00e9lectionn\u00e9. Le mode hybride utilise d\u2019abord le local, puis le cloud si n\u00e9cessaire.',
      'local_ai_mode': 'Local',
      'cloud_ai_mode': 'Cloud',
      'hybrid_ai_mode': 'Hybride',
      'preferred_cloud_provider': 'Fournisseur cloud pr\u00e9f\u00e9r\u00e9',
      'preferred_cloud_provider_subtitle':
          'Utilis\u00e9 lorsque le routage cloud est disponible.',
      'updates': 'Mises \u00e0 jour',
      'updates_subtitle': 'Canaux et v\u00e9rification des mises \u00e0 jour',
      'release_channel': 'Canal de publication',
      'check_updates_now': 'V\u00e9rifier maintenant',
      'force_update': 'Forcer la mise \u00e0 jour',
      'force_update_started': 'Mise \u00e0 jour forc\u00e9e lanc\u00e9e.',
      'force_update_failed': 'La mise \u00e0 jour forc\u00e9e n\u2019a pas pu d\u00e9marrer.',
      'update_idle': 'Aucune v\u00e9rification effectu\u00e9e',
      'up_to_date': 'Application \u00e0 jour',
      'new_version_available': 'Nouvelle version disponible',
      'update_incompatible': 'Version actuelle non compatible',
      'downloading_update': 'T\u00e9l\u00e9chargement de la mise \u00e0 jour\u2026',
      'ready_to_install': 'Pr\u00eat \u00e0 installer',
      'update_error': 'Erreur de mise \u00e0 jour',
      'current_version': 'Version actuelle',
      'latest_version': 'Derni\u00e8re version',
      'dismiss': 'Ignorer',
      'apk_downloaded':
          'APK t\u00e9l\u00e9charg\u00e9. Continuez depuis Param\u00e8tres > Mises \u00e0 jour.',
      'installer_opened':
          'Installateur ouvert. Confirmez l\u2019installation sur Android.',
    },
    'it': {
      'settings': 'Impostazioni',
      'models': 'Modelli',
      'models_subtitle': 'Gestisci modelli AI',
      'personal_data_subtitle': 'Profilo e preferenze',
      'language_subtitle': 'Lingua dell\'app',
      'ai_mode_subtitle': 'Routing runtime e fallback',
      'system_prompt_subtitle': 'Comportamento globale AI',
      'model_validated': 'Valido',
      'model_invalid': 'File non valido',
      'import_url': 'Importa URL',
      'import_local_model': 'Importa GGUF',
      'imported_model': 'Importato',
      'local_model_path': 'Percorso',
      'model_missing_file': 'File mancante',
      'relink_model': 'Ricollega',
      'refresh_models': 'Aggiorna modelli',
      'personal_data_optional': 'Dati personali (opzionale)',
      'name': 'Nome',
      'date_of_birth': 'Data di nascita',
      'profile_data_optional': 'Dati profilo (opzionale)',
      'language': 'Lingua',
      'system_default': 'Predefinita di sistema',
      'english': 'Inglese',
      'french': 'Francese',
      'italian': 'Italiano',
      'spanish': 'Spagnolo',
      'german': 'Tedesco',
      'ai_mode': 'Modalit\u00e0 AI',
      'fast': 'Veloce',
      'balanced': 'Bilanciata',
      'deep_reasoning': 'Ragionamento profondo',
      'system_prompt': 'Prompt di sistema',
      'define_global_ai_behavior': 'Definisci il comportamento globale dell\'AI...',
      'reset_default': 'Ripristina predefinito',
      'save': 'Salva',
      'close': 'Chiudi',
      'install': 'Installa',
      'settings_saved': 'Impostazioni salvate',
      'import_model_from_url': 'Importa modello da URL',
      'model_url': 'URL modello',
      'display_name_optional': 'Nome visualizzato (opzionale)',
      'cancel': 'Annulla',
      'import': 'Importa',
      'url_required': 'URL obbligatorio',
      'valid_http_url': 'Inserisci un URL http/https valido',
      'ai_orchestrator': 'AI Orchestrator',
      'chat': 'Chat',
      'start_conversation': 'Inizia una conversazione',
      'no_local_model': 'Nessun modello locale',
      'message_hint': 'Messaggio\u2026',
      'select_ai_provider': 'Seleziona provider AI',
      'starting_local_intelligence': 'Avvio intelligenza locale\u2026',
      'continue': 'Continua',
      'get_started': 'Inizia',
      'tell_us_about_you': 'Parlaci di te',
      'personalize_experience': 'Personalizza la tua esperienza AI Orchestrator.',
      'your_name': 'Il tuo nome',
      'name_required': 'Il nome \u00e8 obbligatorio',
      'dob_ddmmyyyy': 'Data di nascita (GG/MM/AAAA)',
      'dob_required': 'La data di nascita \u00e8 obbligatoria',
      'welcome_subtitle': 'Il tuo spazio AI minimale.',
      'checking_updates': 'Controllo aggiornamenti modelli\u2026',
      'choose_model': 'Scegli il tuo modello AI',
      'download_offline_model': 'Scarica un modello per elaborazione AI completamente offline.',
      'recommended_for_device': 'Consigliato per questo dispositivo:',
      'recommended': 'Consigliato',
      'active': 'Attivo',
      'download': 'Scarica',
      'use_this_model': 'Usa questo modello',
      're_download': 'Ri-scarica',
      'update_available': 'Aggiornamento disponibile',
      'update': 'Aggiorna',
      'later': 'Pi\u00f9 tardi',
      'details': 'Dettagli',
      'new_model_version_title': 'Nuova versione del modello disponibile',
      'new_model_version_body': 'Una nuova versione \u00e8 disponibile per:',
      'update_model_confirm': 'Vuoi aggiornare adesso?',
      'runtime_routing_description':
          'La modalit\u00e0 locale usa solo modelli sul dispositivo. La modalit\u00e0 cloud privilegia il provider cloud selezionato. La modalit\u00e0 ibrida usa prima il locale, poi il cloud quando serve.',
      'local_ai_mode': 'Locale',
      'cloud_ai_mode': 'Cloud',
      'hybrid_ai_mode': 'Ibrida',
      'preferred_cloud_provider': 'Provider cloud preferito',
      'preferred_cloud_provider_subtitle':
          'Usato quando il routing cloud \u00e8 disponibile.',
      'updates': 'Aggiornamenti',
      'updates_subtitle': 'Canali update e verifica versioni',
      'local_runtime': 'Runtime locale',
      'voice_engine': 'Motore vocale',
      'mode': 'Modalità',
      'tokens': 'Token',
      'time': 'Tempo',
      'runtime_ready': 'Pronto',
      'runtime_idle': 'Runtime inattivo',
      'runtime_unverified': 'Runtime non verificato',
      'runtime_loading': 'Caricamento',
      'runtime_tokenizing': 'Tokenizzazione',
      'runtime_generating': 'Generazione',
      'runtime_streaming': 'Streaming',
      'runtime_completed': 'Completato',
      'runtime_timed_out': 'Timeout',
      'runtime_stalled': 'Runtime bloccato',
      'runtime_error': 'Errore runtime',
      'runtime_missing_library': 'Libreria mancante',
      'runtime_model_missing': 'Modello mancante',
      'runtime_failed': 'Runtime non riuscito',
      'release_channel': 'Canale release',
      'preferred_release_channel': 'Canale release preferito',
      'check_updates_now': 'Controlla ora',
      'force_update': 'Forza aggiornamento',
      'force_update_started': 'Aggiornamento forzato avviato.',
      'force_update_failed': 'Impossibile avviare l\u2019aggiornamento forzato.',
      'latest_known': 'Ultima rilevata',
      'last_checked': 'Ultimo controllo',
      'already_up_to_date': 'Già aggiornata',
      'update_check_completed': 'Controllo aggiornamenti completato',
      'update_download_title': 'Download aggiornamento',
      'update_idle': 'Aggiornamenti non ancora verificati',
      'up_to_date': 'App aggiornata',
      'new_version_available': 'Nuova versione disponibile',
      'update_incompatible': 'Versione corrente non compatibile',
      'downloading_update': 'Download aggiornamento\u2026',
      'ready_to_install': 'Pronto per installazione',
      'update_error': 'Errore aggiornamento',
      'current_version': 'Versione corrente',
      'latest_version': 'Ultima versione',
      'dismiss': 'Chiudi',
      'apk_downloaded':
          'APK scaricato. Continua da Impostazioni > Aggiornamenti.',
      'installer_opened':
          'Installer aperto. Conferma l\u2019installazione su Android.',
    },
    'es': {
      'settings': 'Configuraci\u00f3n',
      'models': 'Modelos',
      'models_subtitle': 'Gestionar modelos de IA',
      'personal_data_subtitle': 'Perfil y preferencias',
      'language_subtitle': 'Idioma de la app',
      'ai_mode_subtitle': 'Enrutamiento runtime y fallback',
      'system_prompt_subtitle': 'Comportamiento global de la IA',
      'model_validated': 'V\u00e1lido',
      'model_invalid': 'Archivo inv\u00e1lido',
      'import_url': 'Importar URL',
      'import_local_model': 'Importar GGUF',
      'imported_model': 'Importado',
      'local_model_path': 'Ruta',
      'model_missing_file': 'Archivo faltante',
      'relink_model': 'Vincular de nuevo',
      'refresh_models': 'Actualizar modelos',
      'personal_data_optional': 'Datos personales (opcional)',
      'name': 'Nombre',
      'date_of_birth': 'Fecha de nacimiento',
      'profile_data_optional': 'Datos de perfil (opcional)',
      'language': 'Idioma',
      'system_default': 'Predeterminado del sistema',
      'english': 'Ingl\u00e9s',
      'french': 'Franc\u00e9s',
      'italian': 'Italiano',
      'spanish': 'Espa\u00f1ol',
      'german': 'Alem\u00e1n',
      'ai_mode': 'Modo IA',
      'fast': 'R\u00e1pido',
      'balanced': 'Equilibrado',
      'deep_reasoning': 'Razonamiento profundo',
      'system_prompt': 'Prompt del sistema',
      'define_global_ai_behavior': 'Define el comportamiento global de la IA...',
      'reset_default': 'Restablecer',
      'save': 'Guardar',
      'settings_saved': 'Configuraci\u00f3n guardada',
      'import_model_from_url': 'Importar modelo desde URL',
      'model_url': 'URL del modelo',
      'display_name_optional': 'Nombre para mostrar (opcional)',
      'cancel': 'Cancelar',
      'import': 'Importar',
      'url_required': 'Se requiere URL',
      'valid_http_url': 'Introduce una URL http/https v\u00e1lida',
      'ai_orchestrator': 'AI Orchestrator',
      'chat': 'Chat',
      'start_conversation': 'Inicia una conversaci\u00f3n',
      'no_local_model': 'Sin modelo local',
      'message_hint': 'Mensaje\u2026',
      'select_ai_provider': 'Seleccionar proveedor de IA',
      'starting_local_intelligence': 'Iniciando inteligencia local\u2026',
      'continue': 'Continuar',
      'get_started': 'Comenzar',
      'tell_us_about_you': 'Cu\u00e9ntanos sobre ti',
      'personalize_experience': 'Personaliza tu experiencia AI Orchestrator.',
      'your_name': 'Tu nombre',
      'name_required': 'El nombre es obligatorio',
      'dob_ddmmyyyy': 'Fecha de nacimiento (DD/MM/AAAA)',
      'dob_required': 'La fecha de nacimiento es obligatoria',
      'welcome_subtitle': 'Tu espacio de IA minimalista.',
      'checking_updates': 'Buscando actualizaciones de modelos\u2026',
      'choose_model': 'Elige tu modelo de IA',
      'download_offline_model': 'Descarga un modelo para procesamiento de IA totalmente offline.',
      'recommended_for_device': 'Recomendado para este dispositivo:',
      'recommended': 'Recomendado',
      'active': 'Activo',
      'download': 'Descargar',
      'use_this_model': 'Usar este modelo',
      're_download': 'Re-descargar',
      'update_available': 'Actualizaci\u00f3n disponible',
      'update': 'Actualizar',
      'later': 'M\u00e1s tarde',
      'details': 'Detalles',
      'new_model_version_title': 'Nueva versi\u00f3n de modelo disponible',
      'new_model_version_body': 'Una nueva versi\u00f3n est\u00e1 disponible para:',
      'update_model_confirm': '\u00bfDeseas actualizar ahora?',
      'runtime_routing_description':
          'El modo local usa solo modelos en el dispositivo. El modo cloud prioriza el proveedor cloud seleccionado. El modo h\u00edbrido usa primero lo local y luego cloud cuando hace falta.',
      'local_ai_mode': 'Local',
      'cloud_ai_mode': 'Cloud',
      'hybrid_ai_mode': 'H\u00edbrido',
      'preferred_cloud_provider': 'Proveedor cloud preferido',
      'preferred_cloud_provider_subtitle':
          'Se usa cuando el enrutamiento cloud est\u00e1 disponible.',
      'updates': 'Actualizaciones',
      'updates_subtitle': 'Canales y comprobaci\u00f3n de actualizaciones',
      'release_channel': 'Canal de lanzamiento',
      'check_updates_now': 'Comprobar ahora',
      'force_update': 'Forzar actualizaci\u00f3n',
      'force_update_started': 'Actualizaci\u00f3n forzada iniciada.',
      'force_update_failed': 'No se pudo iniciar la actualizaci\u00f3n forzada.',
      'update_idle': 'Actualizaciones a\u00fan no comprobadas',
      'up_to_date': 'Aplicaci\u00f3n actualizada',
      'new_version_available': 'Nueva versi\u00f3n disponible',
      'update_incompatible': 'La versi\u00f3n actual no es compatible',
      'downloading_update': 'Descargando actualizaci\u00f3n\u2026',
      'ready_to_install': 'Lista para instalar',
      'update_error': 'Error de actualizaci\u00f3n',
      'current_version': 'Versi\u00f3n actual',
      'latest_version': '\u00daltima versi\u00f3n',
      'dismiss': 'Descartar',
      'apk_downloaded':
          'APK descargado. Contin\u00faa desde Ajustes > Actualizaciones.',
      'installer_opened':
          'Instalador abierto. Confirma la instalaci\u00f3n en Android.',
    },
    'de': {
      'settings': 'Einstellungen',
      'models': 'Modelle',
      'models_subtitle': 'KI-Modelle verwalten',
      'personal_data_subtitle': 'Profil & Einstellungen',
      'language_subtitle': 'App-Sprache',
      'ai_mode_subtitle': 'Runtime-Routing und Fallback',
      'system_prompt_subtitle': 'Globales KI-Verhalten',
      'model_validated': 'G\u00fcltig',
      'model_invalid': 'Ung\u00fcltige Datei',
      'import_url': 'URL importieren',
      'import_local_model': 'GGUF importieren',
      'imported_model': 'Importiert',
      'local_model_path': 'Pfad',
      'model_missing_file': 'Datei fehlt',
      'relink_model': 'Neu verkn\u00fcpfen',
      'refresh_models': 'Modelle aktualisieren',
      'personal_data_optional': 'Pers\u00f6nliche Daten (optional)',
      'name': 'Name',
      'date_of_birth': 'Geburtsdatum',
      'profile_data_optional': 'Profildaten (optional)',
      'language': 'Sprache',
      'system_default': 'Systemstandard',
      'english': 'Englisch',
      'french': 'Franz\u00f6sisch',
      'italian': 'Italienisch',
      'spanish': 'Spanisch',
      'german': 'Deutsch',
      'ai_mode': 'KI-Modus',
      'fast': 'Schnell',
      'balanced': 'Ausgewogen',
      'deep_reasoning': 'Tiefes Denken',
      'system_prompt': 'System-Prompt',
      'define_global_ai_behavior': 'Globales KI-Verhalten festlegen...',
      'reset_default': 'Standard zur\u00fccksetzen',
      'save': 'Speichern',
      'settings_saved': 'Einstellungen gespeichert',
      'import_model_from_url': 'Modell von URL importieren',
      'model_url': 'Modell-URL',
      'display_name_optional': 'Anzeigename (optional)',
      'cancel': 'Abbrechen',
      'import': 'Importieren',
      'url_required': 'URL ist erforderlich',
      'valid_http_url': 'G\u00fcltige http/https-URL eingeben',
      'ai_orchestrator': 'AI Orchestrator',
      'chat': 'Chat',
      'start_conversation': 'Konversation starten',
      'no_local_model': 'Kein lokales Modell',
      'message_hint': 'Nachricht\u2026',
      'select_ai_provider': 'KI-Anbieter w\u00e4hlen',
      'starting_local_intelligence': 'Lokale Intelligenz wird gestartet\u2026',
      'continue': 'Weiter',
      'get_started': 'Loslegen',
      'tell_us_about_you': 'Erz\u00e4hl uns von dir',
      'personalize_experience': 'Personalisiere dein AI-Orchestrator-Erlebnis.',
      'your_name': 'Dein Name',
      'name_required': 'Name ist erforderlich',
      'dob_ddmmyyyy': 'Geburtsdatum (TT/MM/JJJJ)',
      'dob_required': 'Geburtsdatum ist erforderlich',
      'welcome_subtitle': 'Dein minimalistischer KI-Arbeitsbereich.',
      'checking_updates': 'Suche nach Modell-Updates\u2026',
      'choose_model': 'W\u00e4hle dein KI-Modell',
      'download_offline_model': 'Lade ein Modell f\u00fcr vollst\u00e4ndig offline KI-Verarbeitung herunter.',
      'recommended_for_device': 'Empfohlen f\u00fcr dieses Ger\u00e4t:',
      'recommended': 'Empfohlen',
      'active': 'Aktiv',
      'download': 'Herunterladen',
      'use_this_model': 'Dieses Modell verwenden',
      're_download': 'Erneut herunterladen',
      'update_available': 'Update verf\u00fcgbar',
      'update': 'Aktualisieren',
      'later': 'Sp\u00e4ter',
      'details': 'Details',
      'new_model_version_title': 'Neue Modellversion verf\u00fcgbar',
      'new_model_version_body': 'Eine neue Version ist verf\u00fcgbar f\u00fcr:',
      'update_model_confirm': 'M\u00f6chtest du jetzt aktualisieren?',
      'runtime_routing_description':
          'Der lokale Modus verwendet nur Ger\u00e4temodelle. Der Cloud-Modus bevorzugt den ausgew\u00e4hlten Cloud-Anbieter. Der Hybridmodus nutzt zuerst lokal und bei Bedarf Cloud.',
      'local_ai_mode': 'Lokal',
      'cloud_ai_mode': 'Cloud',
      'hybrid_ai_mode': 'Hybrid',
      'preferred_cloud_provider': 'Bevorzugter Cloud-Anbieter',
      'preferred_cloud_provider_subtitle':
          'Wird verwendet, wenn Cloud-Routing verf\u00fcgbar ist.',
      'updates': 'Updates',
      'updates_subtitle': 'Update-Kan\u00e4le und Pr\u00fcfung',
      'release_channel': 'Release-Kanal',
      'check_updates_now': 'Jetzt pr\u00fcfen',
      'force_update': 'Update erzwingen',
      'force_update_started': 'Erzwungenes Update gestartet.',
      'force_update_failed': 'Erzwungenes Update konnte nicht gestartet werden.',
      'update_idle': 'Noch nicht gepr\u00fcft',
      'up_to_date': 'App ist aktuell',
      'new_version_available': 'Neue Version verf\u00fcgbar',
      'update_incompatible': 'Aktuelle Version ist nicht kompatibel',
      'downloading_update': 'Update wird heruntergeladen\u2026',
      'ready_to_install': 'Bereit zur Installation',
      'update_error': 'Update-Fehler',
      'current_version': 'Aktuelle Version',
      'latest_version': 'Neueste Version',
      'dismiss': 'Schlie\u00dfen',
      'apk_downloaded':
          'APK heruntergeladen. Weiter in Einstellungen > Updates.',
      'installer_opened':
          'Installer ge\u00f6ffnet. Installation auf Android best\u00e4tigen.',
    },
  };

  String t(String key) {
    final languageCode = locale.languageCode;
    return _localizedValues[languageCode]?[key] ??
        _localizedValues['en']?[key] ??
        key;
  }
}

class _AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) =>
      const ['en', 'fr', 'it', 'es', 'de'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(covariant LocalizationsDelegate<AppLocalizations> old) =>
      false;
}

extension AppLocalizationsX on BuildContext {
  AppLocalizations get l10n => AppLocalizations.of(this);
}
